####Make sure you use following file structure (using EXACT naming):
# current directory
#   /town01_waypoints
#       town01_waypoints_0.txt
#       town01_waypoints_1.txt
#           .
#           .
#           .
#
#   /town02_waypoints
#       town02_waypoints_0.txt
#       town02_waypoints_1.txt
#           .
#           .
#           .
#   
#   .
#   .
#   .
#   /town10_waypoints
#       town10_waypoints_0.txt
#           .
#           .
#           .
#
#   /town_01_waypoints_annot
#       town_01_waypoints_0_annot_c.txt     #This is generated by script
#       town_01_waypoints_0_annot_m.txt     #This is generated by script
#           .
#           .
#           .
#   .
#   .
#   .
#
#   /town_10_waypoints_annot
#       town_10_waypoints_0_annot_c.txt     #This is generated by script
#       town_10_waypoints_0_annot_m.txt     #This is generated by script

filetown=input("Enter town number (xx): ")
filenum=input("Enter waypoint file number: ")
filename=f"town{filetown}_waypoints/town{filetown}_waypoints_{filenum}.txt"
waypoints=[]
with open(filename,'r') as file:
    lines=file.readlines()
    for line in lines:
        if line is not lines[-1]:
            waypoints.append(eval(line[0:-2]))
        else:
            waypoints.append(eval(line[0:]))
            
import matplotlib.pyplot as plt

x = [x[0] for x in waypoints]
y = [x[1] for x in waypoints]

fig, ax = plt.subplots()
ax.set_aspect('equal', adjustable='box')
ax.plot(x, y, '-')  # Base line
for i in range(len(x) - 1):
  if i%8==0:
      mid_x=(x[i]+x[i+1])/2
      mid_y=(y[i]+y[i+1])/2
      dx = x[i+1]-x[i]
      dy = y[i+1]-y[i]
      ax.annotate('', xy=(x[i+1], y[i+1]),xytext=(mid_x,mid_y),arrowprops=dict(arrowstyle='->',color='red',lw=1.5))          
plt.show()
writeToFile=(input("Continue? (y/n) ")=="y")
print(writeToFile)
if(writeToFile):
    moves_list=[]
    coord_list=[]
    while(True):
        move=input("Enter move (# to stop): ")
        if move=="#":
            break
        else:
            moves_list.append(move)
    
    while(True):
        coord_start=input("Enter start coordinate [x,y]: (# to stop) ")
        coord_stop=input("Enter stop coordinate [x,y]: (# to stop) ")
        if coord_start=="#" or coord_stop=="#":
            break
        else:
            coord_startf=eval(coord_start)
            coord_startf.append(0)
            coord_stopf=eval(coord_stop)
            coord_stopf.append(0)
            coord_list.append([coord_startf,coord_stopf])
    
    file_name_moves= f"town{filetown}_waypoints_annot/town{filetown}_waypoints_{filenum}_annot_m.txt"
    file_name_coords= f"town{filetown}_waypoints_annot/town{filetown}_waypoints_{filenum}_annot_c.txt"
    with open(file_name_moves, 'w') as file:
        file.write(f'{moves_list}')
        print(f"Moves list written to {file_name_moves}")
    with open(file_name_coords, 'w') as file:
        file.write(f'{coord_list}')
        print(f"Moves list written to {file_name_coords}")