# -*- coding: utf-8 -*-
"""complexMovesDict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNM3OSFtMZXISmFf6PXs63ha_ZoJseiM
"""

#As per cardreamer tasks.yaml
#carla_four_lane
#carla_overtake
#carla_right_turn_simple
#carla_right_turn_medium
#carla_right_turn_hard
#carla_right_turn_random
#carla_left_turn_simple
#carla_left_turn_medium
#carla_left_turn_hard
#carla_roundabout
#carla_lane_merge
#carla_traffic_lights
#carla_stop_sign
#carla_follow


complexMovesDict={
    "highway_exit_left": ["carla_overtake","carla_overtake","carla_left_turn_hard","carla_traffic_lights"],
    "highway_exit_right": ["carla_overtake","carla_overtake","carla_right_turn_hard","carla_traffic_lights"],
    "highway_entrance": ["carla_overtake","carla_lane_merge"],
    "cloverleaf_interchange": ["carla_overtake","carla_right_turn_hard","traffic_light"]
    '''TODO: Import Complex Direction List'''
}