# -*- coding: utf-8 -*-
"""parseMultiInstruction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xhR_WA4yQpy7CwDjHWacgWYHDZu2pXx
"""

#Parse multi instruction function
#Takes in command line input as string (argv)
#If 'multi::' flag is recognized in string, returns list of command line input for each unique task
#i.e. 'multi::' -> [command line input task 1, command line input task 2, etc.]
#Else returns list [command line input]
#FORMAT INSTRUCTIONS:
#tasks must be wrapped accordingly: multi::+task1+task2+task3+taskN~

def parseMultiInstruction(argv=None,complexMovesDict=None):
  if(complexMovesDict is not None):
    if 'multi::' in argv:
      task_argvs=[]
      argv_split=argv.split()
      for idx, word in enumerate(argv_split):
        if 'multi::' in word:
          task_word=word
          splitIdx=idx
      argv_without_task=argv_split[:splitIdx]+['#']+argv_split[splitIdx+1:]
      argv_without_task=' '.join(argv_without_task)
      task_word=task_word.replace('multi::','')
      tasks=complexMovesDict[task_word]
      for task in tasks:
          task_argvs.append(argv_without_task.replace('#', task))
      return task_argvs
  else:
    if 'multi::' in argv:
      task_argvs=[]
      argv_split=argv.split()
      for idx, word in enumerate(argv_split):
        if 'multi::' in word:
          task_word=word
          splitIdx=idx
      argv_without_task=argv_split[:splitIdx]+['#']+argv_split[splitIdx+1:]
      argv_without_task=' '.join(argv_without_task)
      task_word=''.join(' ' if char in '+~' else char for idx, char in enumerate(task_word))
      tasks=task_word.split()
      for task in tasks:
        if task != 'multi::':
          task_argvs.append(argv_without_task.replace('#', task))
      return task_argvs
    else:
      return [argv]


#Example Outputs:

#Enter command line input: --task multi::+left_turn+right_turn+straight~ --xyz abcdefg
#['--task left_turn --xyz abcdefg', '--task right_turn --xyz abcdefg', '--task straight --xyz abcdefg']

#Enter command line input: --task left_turn --xyz abcdefg
#['--task left_turn --xyz abcdefg']